-- ERD 원본에 빠져 있던 것 보완: PK AUTO_INCREMENT, 외래키, 중복 방지
-- schema.sql 실행 후 이어서 실행
USE ai_compass;

ALTER TABLE Users     MODIFY user_id     INT NOT NULL AUTO_INCREMENT;
ALTER TABLE AI_Models MODIFY model_id    INT NOT NULL AUTO_INCREMENT;
ALTER TABLE Reviews   MODIFY review_id   INT NOT NULL AUTO_INCREMENT;
ALTER TABLE Favorites MODIFY favorite_id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE Pipelines MODIFY pipeline_id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE Users     ADD CONSTRAINT UQ_USERS_EMAIL UNIQUE (email);
ALTER TABLE Favorites ADD CONSTRAINT UQ_FAVORITES UNIQUE (user_id, model_id);

ALTER TABLE Reviews   ADD CONSTRAINT FK_REVIEWS_MODEL   FOREIGN KEY (model_id) REFERENCES AI_Models (model_id) ON DELETE CASCADE;
ALTER TABLE Reviews   ADD CONSTRAINT FK_REVIEWS_USER    FOREIGN KEY (user_id)  REFERENCES Users (user_id)      ON DELETE CASCADE;
ALTER TABLE Favorites ADD CONSTRAINT FK_FAVORITES_USER  FOREIGN KEY (user_id)  REFERENCES Users (user_id)      ON DELETE CASCADE;
ALTER TABLE Favorites ADD CONSTRAINT FK_FAVORITES_MODEL FOREIGN KEY (model_id) REFERENCES AI_Models (model_id) ON DELETE CASCADE;
ALTER TABLE Pipelines ADD CONSTRAINT FK_PIPELINES_USER  FOREIGN KEY (user_id)  REFERENCES Users (user_id)      ON DELETE CASCADE;
